### ISSUE TITLE
This is the fix

### ISSUE THREAD

**Issue by renalpha** [chrisbrown-io/capacitor-ios-video-issue#1]
https://gist.github.com/renalpha/a4092c7fd205dfb13f84c70edb079663

This is the fix PartialContent , its a policy by ios

**Comment by chrisbrown-io** [comment]
Thanks for the issue/comment. I presume you've ended up here from <https://github.com/ionic-team/capacitor/issues/6790>.

As you've mentioned, handling HTTP 206 requests is required – but capacitor already handles this for local files as it should (<https://github.com/ionic-team/capacitor/blob/main/ios/Capacitor/Capacitor/WebViewAssetHandler.swift#L51>).

The issue is that on specific versions of iOS (16.5.x), the `Range` requested is incorrect/inconsistent with the `Content-Length` header returned by the initial request (handled by capacitor), which prevents the video from playing. This seems to be a bug within Safari itself that I am yet to find a solution for.

In your example, you're proxying video requests via a PHP script that would need to be hosted and served from a remote server – and remote videos in general play back correctly on (16.5.x), which isn't the issue in question.

Thanks for your input regardless!
